### PR TITLE
SETI-2159 - Use standard GD java-library lifecycle

### PR DESCRIPTION
**Pull request by pgressa**

### CODE REVIEW

**Comment by michalvanco** [comment]
ok to test

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gearman-plugin-opensource-repository-check/1/ : SUCCESS in 7s
- https://checklist.intgdc.com/job/java-libraries/job/gearman-plugin-tests-zuul-el7/1/ : FAILURE in 4m 24s

**Comment by pgressa** [comment]
ok to test

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gearman-plugin-opensource-repository-check/2/ : SUCCESS in 34s
- https://checklist.intgdc.com/job/java-libraries/job/gearman-plugin-tests-zuul-el7/2/ : SUCCESS in 4m 55s

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/compliance/job/gearman-plugin-merge-compliance-check/1/ : SUCCESS in 14s
- https://checklist.intgdc.com/job/java-libraries/job/gearman-plugin-tests-zuul-el7/3/ : SUCCESS in 5m 49s

**Pull request merged**
