### PR TITLE
Update from upstream 0.4.1

### PR DESCRIPTION
**Pull request by tomaso**

### CODE REVIEW

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gearman-plugin-oss-check/24/ : SUCCESS in 6s
- https://checklist.intgdc.com/job/java-libraries/job/gearman-plugin-tests-zuul-el7/46/ : FAILURE in 2m 25s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gearman-plugin-oss-check/25/ : SUCCESS in 8s
- https://checklist.intgdc.com/job/java-libraries/job/gearman-plugin-tests-zuul-el7/47/ : SUCCESS in 4m 06s

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/compliance/job/gearman-plugin-merge-compliance-check/7/ : SUCCESS in 28s
- https://checklist.intgdc.com/job/compliance/job/gearman-plugin-fossa-scanning-zuul-el7/1/ : FAILURE in 5m 16s (non-voting)
- https://checklist.intgdc.com/job/java-libraries/job/gearman-plugin-tests-zuul-el7/48/ : SUCCESS in 7m 58s

**Comment by hashar** [comment]
Hello!

When I have migrated the OpenDev Gerrit repository to  https://github.com/jenkinsci/gearman-plugin/  I have also merged a good part of the code made by GoodData. I have just assumed your fork was abandoned and I don't think I have made any attempt to reach out to you.  I am more than happy to hand off / share maintenance with the people from Gooddata :]

I noticed you had to revert f6fe1b2faf65248f590a9f9cffe39a41540c7107 which uses the german-java library I have forked. That is required to support Java 11. The patch with the explanation is https://gerrit.wikimedia.org/r/c/integration/gearman-java/+/655663/

**Pull request merged**
